In [ ]:
#why do we need vectordb?
#A vector is akind of data which consists of both magnitude and direction
#the process of converting a natural language into a vector is called as embeddings

# A vector database is going to store a numerical representation of a natural language 
#use/purpose : consider a customer is going to ask about the insurance policy  (if he asks in open llm like chatgpt it ownt give any result)
#to store such kind of private information of data we use vector database ( vector database will ahve numerical representation of data)
# because with the system the customer is going to ask in natural language based on that it need to give the output so we use vector datbase
# but if we use sql or nosql the customer need to send particular syntax which might not be known to a customer
# the process will be with a client i.e mobile or some chat the user requests some information which is convertd to numerical representation by vector embedding
#it is passed to vector database , in that it is going to find the leaset distance value i.e, neraer closer value back to the user
#we are using the llms with vector datbase because to provide the output in human readable format

#the design will be llm will take input from client and get the output from vector database that layer is known as RAG(reterival argumented generation)
#RAG is  atechnique to build  a soultion  to retrive from the private data
#vanilla rag , agentic rag
#A vector embedding ==> my name is ram ==> [number representation ] ==> [...] the numerical representation is called vector with (n dimensions)

#full satck data science ==> neutral network go through it and understand it the core concept of neural network
#it will help us through out our carrier inthe world of nlp (go through total neural network)
#go through transformers as well

#a vector is an entity which is going to have a magnitude and direction

#a scalar which has only magnitude


#resume projects

In [2]:
pip install requests

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-cd6d7b4c75a2157609fe31bb05673f05b27a6da11968b30c7dc214dc8c14e159"

payload = {
    "input": "my name is ram",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})

print(response.json())

{'object': 'list', 'data': [{'object': 'embedding', 'embedding': [0.0224761962890625, -0.034637451171875, -0.05316162109375, -0.0166473388671875, -0.057861328125, -0.035247802734375, 0.0086669921875, 0.03955078125, -0.055816650390625, -0.07366943359375, 0.031036376953125, 0.01165008544921875, -0.045257568359375, -0.0243682861328125, -0.0092315673828125, 0.01445770263671875, 0.0028285980224609375, -0.01763916015625, -0.0038738250732421875, 0.041900634765625, 0.03790283203125, 0.0078277587890625, 0.024810791015625, 0.035919189453125, 0.005107879638671875, 0.04278564453125, 0.005352020263671875, 0.029388427734375, 0.06207275390625, -0.0816650390625, 0.0122222900390625, -0.028411865234375, 0.03826904296875, -0.06817626953125, 0.031829833984375, -0.0248260498046875, 0.027618408203125, -0.04278564453125, -0.020294189453125, 0.0338134765625, -0.0005431175231933594, 0.00316619873046875, 0.04547119140625, 0.019012451171875, -0.005584716796875, -0.0025787353515625, -0.0751953125, 0.0099639892578

In [7]:
result = response.json()

In [10]:
len(result['data'][0]['embedding'])

1536

In [11]:
#1536 is nothing but a dimension
a = result['data'][0]['embedding']

In [12]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-cd6d7b4c75a2157609fe31bb05673f05b27a6da11968b30c7dc214dc8c14e159"

payload = {
    "input": "ram is a genai student",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})

b = response.json()['data'][0]['embedding']

In [13]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-cd6d7b4c75a2157609fe31bb05673f05b27a6da11968b30c7dc214dc8c14e159"

payload = {
    "input": "ram used to work as fsd",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})

c = response.json()['data'][0]['embedding']

In [14]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-cd6d7b4c75a2157609fe31bb05673f05b27a6da11968b30c7dc214dc8c14e159"

payload = {
    "input": "what ram does",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})

inp = response.json()['data'][0]['embedding']

In [19]:
 

import numpy as np

In [16]:
type(a)

list

In [20]:
a = np.array(a)
b = np.array(b)
c = np.array(c)
inp = np.array(inp)

In [21]:
a,b,c,inp

(array([ 0.0224762 , -0.03463745, -0.05316162, ...,  0.0137558 ,
         0.01242828,  0.00104809], shape=(1536,)),
 array([ 0.01763916,  0.00735855, -0.00649643, ..., -0.01731873,
         0.02319336,  0.00336456], shape=(1536,)),
 array([-0.01308441, -0.02565002,  0.05307007, ...,  0.03436279,
        -0.00235558, -0.00148392], shape=(1536,)),
 array([-0.00240135, -0.01000977,  0.0133667 , ..., -0.00847626,
        -0.00271797,  0.02542114], shape=(1536,)))

In [ ]:
#to find an answer need to find distance between inp->a,b,c
dist_inp_a = np.linalg.norm(inp-a) #linalg == linearalgebra
dist_inp_b = np.linalg.norm(inp-b)
dist_inp_c = np.linalg.norm(inp-c)


In [ ]:
dist_inp_a,dist_inp_b,dist_inp_c

#euclidance distance
#squareroot of (x1- x2) square + (y1-y2) square + (z1-z2) square

(np.float64(0.8940279999195553),
 np.float64(0.9952100032600067),
 np.float64(0.9564330207608313))

In [ ]:
# the nearest distance is 0.89 

In [ ]:
#facebook ai similarity search (faiss) ==> type of vector database (v.v.vimp)
